secretGenerator:
- name: mysql
  env: mysql.txt

configMapGenerator:
  - name: frontend
    literals:
      - api-endpoint="https:\/\/ifdevops.ga\/api\/"
resources:
  - db-deployment.yaml
  - be-deployment.yaml
  - fe-deployment.yaml
  - ingress.yaml
