apiVersion: v1
kind: Service
metadata:
  name: dtapi-mysql
  labels:
    app: dtapi
spec:
  ports:
    - port: 3306
  selector:
    app: dtapi
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtapi-mysql
  labels:
    app: dtapi
spec:
  selector:
    matchLabels:
      app: dtapi
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dtapi
        tier: mysql
    spec:
      containers:
      - image: eu.gcr.io/test1-286117/dtapi-mysql:latest
        name: mysql
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: user_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql
              key: database
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: root_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: data
      volumes:
      - name: mysql-persistent-storage
        gcePersistentDisk:
          pdName: dtapi-mysql
