apiVersion: v1
kind: Service
metadata:
  name: dtapi-be
  labels:
    app: dtapi
spec:
  ports:
    - port: 80
  selector:
    app: dtapi
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtapi-be
  labels:
    app: dtapi
spec:
  selector:
    matchLabels:
      app: dtapi
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dtapi
        tier: backend
    spec:
      containers:
      - image: eu.gcr.io/test1-286117/dtapi-be:latest
        name: dtapi
        env:
        - name: MYSQL_HOST
          value: dtapi-mysql
        ports:
        - containerPort: 80
          name: dtapi
