apiVersion: v1
kind: Service
metadata:
  name: dtapi-mysql
  labels:
    app: dtapi
spec:
  ports:
    - port: 3306
  selector:
    app: dtapi
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: dtapi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtapi-mysql
  labels:
    app: dtapi
spec:
  selector:
    matchLabels:
      app: dtapi
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dtapi
        tier: mysql
    spec:
      containers:
      - image: eu.gcr.io/test1-286117/dtapi-mysql:1.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db
              key: database
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: data
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
