apiVersion: v1
kind: Service
metadata:
  name: dtapi-lb
  labels:
    app: dtapi
spec:
  ports:
    - port: 80
  selector:
    app: dtapi
    tier: nginx-lb
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtapi-lb
  labels:
    app: dtapi
spec:
  selector:
    matchLabels:
      app: dtapi
      tier: nginx-lb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dtapi
        tier: nginx-lb
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.2-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: false
      volumes:
        - name: config
          configMap:
            name: dtapi-nginx-config
            items:
            - key: nginx-conf
              path: "default.conf"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dtapi-nginx-config
data:
  nginx-conf: |
    upstream be {
      server dtapi-be;
    }
    #upstream fe {
    #  server dtapi-fe;
    #}
    server {
      listen 80;
      location ^~ /api {
        proxy_pass http://be/api;
      }
     # location ~ ^/.*$ {
     #   proxy_pass http://fe;
     # }
    }
