secretGenerator:
- name: mysql
  literals:
    - database=dtapi2
    - user=dtapi
    - user_password=dtapi
    - root_password=rootdtapi

resources:
  - dtapi-db-deployment.yaml
  - dtapi-be-deployment.yaml
  - dtapi-fe-deployment.yaml
  - dtapi-ingress.yaml
